In [7]:
import pandas as pd
import numpy as np

In [2]:
my_df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')

my_df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [3]:
new_df = my_df.head(50)
new_df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,7,1,Chips and Guacamole,NaN,$4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
18,9,2,Canned Soda,[Sprite],$2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
20,10,1,Chips and Guacamole,NaN,$4.45
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",$10.98
24,12,1,Izze,[Grapefruit],$3.39
25,13,1,Chips and Fresh Tomato Salsa,NaN,$2.39
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99
28,14,1,Canned Soda,[Dr. Pepper],$1.09
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
30,15,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
31,16,1,Steak Burrito,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",$8.99
32,16,1,Side of Chips,NaN,$1.69
33,17,1,Carnitas Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99
34,17,1,Bottled Water,NaN,$1.09
35,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, Rice]",$8.75
36,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75
37,18,1,Chips and Guacamole,NaN,$4.45
38,18,1,Chips and Tomatillo Green Chili Salsa,NaN,$2.95
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.75
40,19,1,Chips,NaN,$2.15
41,20,1,Chips and Guacamole,NaN,$4.45
42,20,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$11.25
43,20,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$11.75
44,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75
45,21,1,Chicken Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$10.98
46,21,1,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Fajit...",$8.99
47,21,1,Izze,[Blackberry],$3.39
48,22,1,Steak Burrito,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.99
49,22,1,Chips and Guacamole,NaN,$3.99

In [8]:
items_price = np.array(new_df['item_price'].str.replace('$', ''))
items_price

array(['2.39 ', '3.39 ', '3.39 ', '2.39 ', '16.98 ', '10.98 ', '1.69 ',
       '11.75 ', '9.25 ', '9.25 ', '4.45 ', '8.75 ', '8.75 ', '11.25 ',
       '4.45 ', '2.39 ', '8.49 ', '8.49 ', '2.18 ', '8.75 ', '4.45 ',
       '8.99 ', '3.39 ', '10.98 ', '3.39 ', '2.39 ', '8.49 ', '8.99 ',
       '1.09 ', '8.49 ', '2.39 ', '8.99 ', '1.69 ', '8.99 ', '1.09 ',
       '8.75 ', '8.75 ', '4.45 ', '2.95 ', '11.75 ', '2.15 ', '4.45 ',
       '11.25 ', '11.75 ', '8.75 ', '10.98 ', '8.99 ', '3.39 ', '8.99 ',
       '3.99 '], dtype=object)

In [9]:
new_df["price_without_$"] = items_price
new_df

,order_id,quantity,item_name,choice_description,item_price,price_without_$
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
1,1,1,Izze,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98,10.98
6,3,1,Side of Chips,NaN,$1.69,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25,9.25
10,5,1,Chips and Guacamole,NaN,$4.45,4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75,8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,11.25
14,7,1,Chips and Guacamole,NaN,$4.45,4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49,8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49,8.49
18,9,2,Canned Soda,[Sprite],$2.18,2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75,8.75
20,10,1,Chips and Guacamole,NaN,$4.45,4.45
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99,8.99
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",$10.98,10.98
24,12,1,Izze,[Grapefruit],$3.39,3.39
25,13,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49,8.49
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99,8.99
28,14,1,Canned Soda,[Dr. Pepper],$1.09,1.09
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49,8.49
30,15,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
31,16,1,Steak Burrito,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",$8.99,8.99
32,16,1,Side of Chips,NaN,$1.69,1.69
33,17,1,Carnitas Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
34,17,1,Bottled Water,NaN,$1.09,1.09
35,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, Rice]",$8.75,8.75
36,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75,8.75
37,18,1,Chips and Guacamole,NaN,$4.45,4.45
38,18,1,Chips and Tomatillo Green Chili Salsa,NaN,$2.95,2.95
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.75,11.75
40,19,1,Chips,NaN,$2.15,2.15
41,20,1,Chips and Guacamole,NaN,$4.45,4.45
42,20,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$11.25,11.25
43,20,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$11.75,11.75
44,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
45,21,1,Chicken Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$10.98,10.98
46,21,1,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Fajit...",$8.99,8.99
47,21,1,Izze,[Blackberry],$3.39,3.39
48,22,1,Steak Burrito,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.99,8.99
49,22,1,Chips and Guacamole,NaN,$3.99,3.99

In [18]:
grouped_df = new_df.groupby('item_name')
grouped_df.count()[["quantity", "item_price"]]

                                       quantity  item_price
item_name
Barbacoa Bowl                                 1           1
Barbacoa Burrito                              1           1
Bottled Water                                 1           1
Canned Soda                                   2           2
Carnitas Bowl                                 1           1
Carnitas Burrito                              1           1
Chicken Bowl                                  6           6
Chicken Burrito                               5           5
Chicken Crispy Tacos                          1           1
Chicken Salad Bowl                            1           1
Chicken Soft Tacos                            3           3
Chips                                         1           1
Chips and Fresh Tomato Salsa                  2           2
Chips and Guacamole                           6           6
Chips and Tomatillo Green Chili Salsa         1           1
Chips and Tomatillo-Green Chili Salsa         3           3
Izze                                          3           3
Nantucket Nectar                              2           2
Side of Chips                                 2           2
Steak Burrito                                 6           6
Steak Soft Tacos                              1           1

In [19]:
new_df.sum()

order_id                                                            603
quantity                                                             52
item_name             Chips and Fresh Tomato SalsaIzzeNantucket Nect...
choice_description    [Clementine][Apple][Tomatillo-Red Chili Salsa ...
item_price            $2.39 $3.39 $3.39 $2.39 $16.98 $10.98 $1.69 $1...
price_without_$       2.39 3.39 3.39 2.39 16.98 10.98 1.69 11.75 9.2...
dtype: object